name: tic_tac_toe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  get: ^4.6.1
  get_storage: ^2.0.2
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

get_cli:
  sub_folder: false

flutter:
  uses-material-design: true
